name: Screenshotbot CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.4.0'

    - name: Check directory structure
      run: |
        pwd
        ls -la
        echo "=== Root directory ==="
        find . -maxdepth 2 -name "*.xcodeproj" -o -name "*.xcworkspace"
        echo "=== ScreenshotbotDemo directory ==="
        ls -la ScreenshotbotDemo/
        find ScreenshotbotDemo/ -maxdepth 2 -name "*.xcodeproj" -o -name "*.xcworkspace"

    - name: List available schemes
      run: |
        xcodebuild -project ScreenshotbotDemo/ScreenshotbotDemo.xcodeproj -list

    - name: List available simulators
      run: |
        xcrun simctl list devices available

    - name: Build and Test
      run: |
        cd ScreenshotbotDemo
        xcodebuild test \
          -project ScreenshotbotDemo.xcodeproj \
          -scheme ScreenshotbotDemo \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro' \
          -enableCodeCoverage YES \
          -derivedDataPath DerivedData

    - name: Find screenshots
      run: |
        find ScreenshotbotDemo/DerivedData -name "*.png" -type f
        find ScreenshotbotDemo/DerivedData -name "*.jpg" -type f

    - name: Run Screenshotbot
      run: |
        curl -L -o screenshotbot "https://github.com/screenshotbot/screenshotbot-cli/releases/latest/download/screenshotbot-macos"
        chmod +x screenshotbot
        ./screenshotbot \
          --api-key=${{ secrets.SCREENSHOTBOT_API_KEY }} \
          --channel=ci \
          --directory=ScreenshotbotDemo/DerivedData/Logs/Test \
          --fail-on-regression=true

    - name: Upload test artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          ScreenshotbotDemo/DerivedData/Logs/Test/
          ScreenshotbotDemo/DerivedData/Logs/Test/*.png
          ScreenshotbotDemo/DerivedData/Logs/Test/*.jpg
        if-no-files-found: warn
        retention-days: 30
