name: SwiftTesting CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.4.0'

    - name: Check directory structure
      run: |
        pwd
        ls -la
        echo "=== Test directory ==="
        ls -la ScreenshotbotDemoTests/
        echo "=== Checking for reference images ==="
        find . -name "__Snapshots__" -type d || echo "No __Snapshots__ directory found"

    - name: List available schemes
      run: |
        xcodebuild -project ScreenshotbotDemo.xcodeproj -list

    - name: List available simulators
      run: |
        xcrun simctl list devices available

    - name: Build project
      run: |
        xcodebuild build \
          -project ScreenshotbotDemo.xcodeproj \
          -scheme ScreenshotbotDemo \
          -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.5' \
          -derivedDataPath DerivedData

    - name: Run tests with record mode
      continue-on-error: true
      env:
        SNAPSHOT_TESTING_RECORD: true
      run: |
        echo "=== Running Swift Tests ==="
        swift test --enable-code-coverage
        
        echo "=== Running Xcode Tests ==="
        xcodebuild test \
          -project ScreenshotbotDemo.xcodeproj \
          -scheme ScreenshotbotDemo \
          -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.5' \
          -enableCodeCoverage YES \
          -derivedDataPath DerivedData \
          -resultBundlePath TestResults.xcresult

    - name: Find generated files
      if: always()
      run: |
        echo "=== Finding all PNG files ==="
        find . -name "*.png" -type f | head -20
        
        echo "=== Finding __Snapshots__ directories ==="
        find . -name "__Snapshots__" -type d
        
        echo "=== Checking DerivedData structure ==="
        find DerivedData -type d -name "*Test*" | head -10
        
        echo "=== Checking for attachment directories ==="
        find DerivedData -type d -name "Attachments" | head -10

    - name: Upload all artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: all-artifacts
        path: |
          **/__Snapshots__/
          DerivedData/
          TestResults.xcresult
        if-no-files-found: warn
        retention-days: 30

    - name: Create summary
      if: always()
      run: |
        echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [ "${{ job.status }}" == "success" ]; then
          echo "✅ Build completed successfully" >> $GITHUB_STEP_SUMMARY
        else
          echo "⚠️ Build completed with issues" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Next Steps" >> $GITHUB_STEP_SUMMARY
          echo "1. Download the 'all-artifacts' from this build" >> $GITHUB_STEP_SUMMARY
          echo "2. Look for generated reference images" >> $GITHUB_STEP_SUMMARY
          echo "3. Commit any reference images to your repository" >> $GITHUB_STEP_SUMMARY
        fi
